pthread_create : pthread_create.c
	gcc pthread_create.c -o pthread_create -lpthread

more_pthread : more_pthread.c
	gcc more_pthread.c -o more_pthread -lpthread

share_pthread : share_pthread.c
	gcc share_pthread.c -o share_pthread -lpthread

pthread_exit_join : pthread_exit_join.c
	gcc pthread_exit_join.c -o pthread_exit_join -lpthread
	
pthread_loop_join : pthread_loop_join.c
	gcc pthread_loop_join.c -o pthread_loop_join -lpthread

main : main.c 
	gcc main.c -o main -lpthread

demo : demo.c
	gcc demo.c -o demo -lpthread